on:
  workflow_dispatch:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 21 20 * * *
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: apk add nodejs npm
    - run: ls
    - run: npm install
    - run: ls 
    - run: cat package-lock.json
    - run: git config --global --add safe.directory /__w/juice-shop/juice-shop
    - run: git config --global user.email "david@hazardsec.com"
    - run: git config --global user.name "hazardsec"
    - run: git add -f package-lock.json
    - run: git commit -m "Container package-lock.json"
    - run: git push
    - run: semgrep ci
